name: Update README
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  actions: write

jobs:
  add-latest-blog-posts:
    name: Add latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://r0x0d.com/feed.xml"
